variables:
  docker_image_tag: $(Build.BuildId)
  project_name: iu-occupancy-prediction-api
  docker_image_name: iunera/$(project_name)

trigger:
  branches:
    include:
      - refs/heads/master

resources:
  repositories:
    - repository: templates
      type: github
      name: iunera/azure-devops-templates

stages:
  - template: docker_and_helm/azure-pipelines.yml@templates
    parameters:
      file_type_to_copy: helm
